### ISSUE TITLE
How to disable the access log?

### ISSUE THREAD

**Issue by mindw** [kubernetes-sigs/dashboard-metrics-scraper#21]
##### Environment

```
Installation method: kubectl apply
Kubernetes version: 1.14
Dashboard version: 2.0.0-b4
Operating system: Linux
```

##### Steps to reproduce
Run the sidecar inside the dashboard pod::
```
        args:
          - --metric-resolution=30s
          - --log-level=warn
        ports:
        - containerPort: 8000
          name: http
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
```
Get logs:
`kubectl -n kube-system logs svc/kubernetes-dashboard -c dashboard-metrics-scraper`

##### Observed result
```
10.0.7.85 - - [20/Sep/2019:23:47:15 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.13"
10.0.7.85 - - [20/Sep/2019:23:47:25 +0000] "GET / HTTP/1.1" 200 6 "" "kube-probe/1.13"
127.0.0.1 - - [20/Sep/2019:23:47:31 +0000] "GET /healthz?timeout=32s HTTP/1.1" 200 25 "" "dashboard/v0.0.0 (linux/amd64) kubernetes/$Format"
```
##### Expected result
An empty log except for warning messages.

##### Comments
- Looks like the sidecar uses gorilla combined logging handler. Couldn't find a way to disable it.
- That format is inconsistent with the rest of the k8s components which use klog. Makes writing a parser harder than it should be.
https://github.com/kubernetes/kubernetes/issues/61006
https://github.com/kubernetes/klog
