### ISSUE TITLE
dashboard-metrics-scrapper

### ISSUE THREAD

**Issue by dioguerra** [kubernetes-sigs/dashboard-metrics-scraper#4]
Do i need to specifically configure with the -kubeconfig path?

Shouldn't the container get the credentials from the metrics-server service account to access the cluster?

Can you share an example of your configuration?

This is the spec from the deployment i have:

```yaml
  spec:
      containers:
      - command:
        - /metrics-server
        - --logtostderr
        image: gcr.io/google_containers/metrics-server-amd64:v0.3.1
        imagePullPolicy: IfNotPresent
        name: metrics-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /metrics-sidecar
        image: dashboard-metrics-scraper:latest
        imagePullPolicy: IfNotPresent
        name: dashboard-metrics-scraper
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: metrics-server
      serviceAccountName: metrics-server
      terminationGracePeriodSeconds: 30
```
